apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deno-ingress
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: app.ostepopp.site
      http:
        paths:
          - path: "/deno(/|$)(.*)"
            pathType: Prefix
            backend:
              service:
                name: deno-app
                port:
                  number: 80
