kind: Service
apiVersion: v1
metadata:
  name: deno-app
  namespace: apps
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "letsencrypt2023"
  labels:
    k8s-app: deno-app
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    k8s-app: deno-app
  type: LoadBalancer
